spring:
  rabbitmq:
    port: 5672
    username: root
    password: root
    host: 192.168.236.128
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
env: test

