spring:
  rabbitmq:
    port: 5672
    username: root
    password: root
    host: 192.168.236.128
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8
  jpa:
    show-sql: true
